ceph.spec.in: drop ceph-rpmlintrc
This source file causes buildpackages/any to fail with:

error: Bad file: /tmp/release/SUSE_LINUX/WORKDIR/SOURCES/ceph-rpmlintrc: No
such file or directory

Signed-off-by: Nathan Cutler <ncutler@suse.com>